### ISSUE TITLE
Headset button doesn't work 

### ISSUE THREAD

**Issue by LobsterJohnson** [M1cha/android_device_xiaomi_aries#37] opened 2014-03-21 12:42 UTC
Hi,
I installed the latest version of your port (cm-11-20140319-UNOFFICIAL-aries.zip).
I switched from cofface's version because your's is updated more frequently and based Nexus 4.

Fact is, my headphone button doesn't work no more (no play/pause etc.).
Sound and microphone work fine though, and if the option is checked CM also launches the music player.
I know this was brought up for former version, just thought I'd confirm it still doesn't work.

**Comment by M1cha** [comment] 2014-05-25 12:52
this is a duplicate of #5 but thx for the confirmation, that it still doesn't work.

**Closed as completed by M1cha** 2014-05-25 12:52 UTC
Labels: duplicate
