### ISSUE TITLE
Charging with PC USB port not working

### ISSUE THREAD

**Issue by Ryotsuke** [M1cha/android_device_xiaomi_aries#15] opened 2013-11-29 08:42 UTC
I guess this can be related to OTG/MHL lack

I had phone on 23%, connected to PC, after some time it was 14%
No charge icon appears

Bug is inconsistent, reboot can temporary fix the issue.

**Comment by M1cha** [comment] 2013-11-29 09:02
Do you have mi2 or mi2s? As far as I know mi2s is the only phone which has this problem.

**Comment by Ryotsuke** [comment] 2013-11-29 09:06
I have Mi2S 32Gb

**Comment by jrizzoli** [comment] 2013-12-02 19:21
so do I own mi2s 16 GB, must reboot to make that he charge. But when i put it, the screen wake up, but it sai discharging.  **%, if I reboot it works well, both Usb and wall charger

**Comment by M1cha** [comment] 2013-12-27 07:29
the whole charging, mhl and otg problems have all todo with  so I each other. The problem is that noone supports OTG so I don't know what's needed.

The new Oppo N1 supports OTG and has a similar chipset. Maybe it will help.

**Comment by jrizzoli** [comment] 2013-12-27 09:00
Ok, now a little report.
I have tested 3 different cables, both on PC and wall charger: Lg one, Asus' and Xiaomi one.

-LG calbe: 80% it works at the first, 10% phone looks like charging\* , and 10% doesn't work at all.
-Asus 60% Phone Looks like charging\* and 40% doesn't work at all.
-Xiaomi 40% it works at the first, 40% doesn't work at all, 20% look like charging*. (with this, if it's working at the first, phone tell me that's cherging via usb, both if it's on pc or wall charger)

So the best here is LG one, do not know why, maybe it is useful, I don't have dmesg here, but it's the same on all the cable, 

*(icon on statusbar "move", Daydream start, but led is off and battery is not charging at all, but the battery log in settings, tell me that it was charging)

**Comment by M1cha** [comment] 2014-01-21 21:18
fixed in 2012-01-21

**Closed as completed by M1cha** 2014-01-21 21:18 UTC
Labels: bug, kernel

**Comment by jrizzoli** [comment] 2014-02-09 19:14
Bug Still here since 07-02-14 on Mi2 S
