### ISSUE TITLE
No in call audio

### ISSUE THREAD

**Issue by ivba7** [M1cha/android_device_xiaomi_aries#69] opened 2014-12-10 09:07 UTC
Have problem with in call audio on Xiaomi mi2s. After I enable mobile data a I can't hear audio during call, ather side can't hear me. After disabling and restarting is audio OK, but only until I enable mobile data again.
I'm on CM11 M12. It started 2 days ago without updating CM. Now I updated CM to latest nightly, but problem still persists.

**Comment by ivba7** [comment] 2014-12-10 10:09
Logs: https://drive.google.com/folderview?id=0B8NSHexALMJIN0d1WEI0RndnS3c&usp=sharing

**Comment by M1cha** [comment] 2014-12-10 10:09
pls post logcat and dmesg logs (dump them right after the failed call, not like 20min later because the logs then could be gone already)

**Comment by M1cha** [comment] 2014-12-10 10:10
lol that was fast ;), I still need dmesg though

**Comment by ivba7** [comment] 2014-12-10 10:37
How can I dump dmesg log?

**Comment by M1cha** [comment] 2014-12-10 10:49
adb shell su -c dmesg > dmesg.log

**Comment by ivba7** [comment] 2014-12-10 11:00
did it. 
Logs: https://drive.google.com/folderview?id=0B8NSHexALMJIN0d1WEI0RndnS3c&usp=sharing

thanks

**Comment by ivba7** [comment] 2014-12-10 13:22
Don't know if it's important, but night before problems started phone's battery was fully drained. Morning I just replaced drained battery with almost fully charched second battery.

**Comment by rfilmyer** [comment] 2014-12-10 16:29
I've been having a similar problem for a few weeks; I'll post `dmesg` logs when it happens to me again. What's logcat?

**Comment by ivba7** [comment] 2014-12-10 16:44
What's happened with problem? Disappeared? Still persists?

**Comment by rfilmyer** [comment] 2014-12-10 19:34
The problem still exists, it might be connected with the most recent update but I'm not sure. It's occasional.

**Comment by rfilmyer** [comment] 2014-12-11 00:56
I've got a folder-full of dmesg logs from this calling bug! I tried different scenarios, and I heard nothing out of the ear speaker for any of them. Then I restarted and everything was working fine.

[logs](https://drive.google.com/folderview?id=0B1CdIkMIIwqNQ1l6bGd2aWNQT3M&usp=sharing)

**Comment by ivba7** [comment] 2014-12-11 17:06
Yesterday did clean install of CM11 M12. Everything was OK. Incall audio worked with wifi, mobile data. Today I rebooted phone and same problem. No incall audio if I turn on WIFI or mobile data after restart. Really frustrating.

**Comment by jrizzoli** [comment] 2014-12-11 17:07
try to use speakervoice when u call someone with mobile data off

2014-12-11 18:06 GMT+01:00 ivba7 notifications@github.com:

**Comment by ivba7** [comment] 2014-12-11 17:31
Did't help. No sound when I use speakerphone or headset.

**Comment by ivba7** [comment] 2014-12-11 19:02
New version of Google play services(6.5.87) and Play store are causing this problem. IF I don't install updates of gapps, everything is ok. If I update it - disable updated gapps, audio is back in normal

**Comment by ivba7** [comment] 2014-12-11 19:06
Found something similar here: https://jira.cyanogenmod.org/browse/CYAN-5728

**Comment by Gonewild87** [comment] 2014-12-13 08:02
Hi, same here as many users on xda. The problem seems to be CheckInService of Google play services. Somebody fixed disabling with an app the service and somebody updated Google play services to a newer version. What is the best choice? Is there anything you can do?

**Comment by ivba7** [comment] 2014-12-13 10:40
I've downgraded google services and everything works.

**Comment by Gonewild87** [comment] 2014-12-13 11:06
Simple guide to downgrade or upgrade Google services?

**Comment by ivba7** [comment] 2014-12-13 18:01
I made clean install of CM11 M12 and flashed older PA gapps form here https://s.basketbuild.com/devs/TKruzze/Android%204.4.4%20GApps/Micro-Modular%20GApps/Older%20Versions

When google play services upgraded itself to version 6.5.87 I uninstalled updates from apllication settings

**Comment by Gonewild87** [comment] 2014-12-13 20:55
Downgrading brings me to an ancient version of Google play services that allows phone calls but not gapps like YouTube and Photos. 

Upgrading to 6.5.99 changes nothing

**Comment by Darthtallgeese** [comment] 2014-12-14 15:41
Temporal solution:

■ Go to Playstore and download the app called "Disable Services",
■ Open and browse to the Google Play Services
■ Disable CheckinServices.
■ Reboot

OK.

**Comment by Gonewild87** [comment] 2014-12-14 15:51
That's what somebody reports about disabling Checkin services:

"Like others, I get increased wake-lock due to msm_hsic_host and sns_async_ev_wakelock. They both took each 40 minutes out of seven hours run resulting in cca 20 % battery life decrease."

**Comment by celebilercem** [comment] 2015-01-04 08:26
Any news? I did a search but could not find any fix :(

**Comment by kozachenko-m** [comment] 2015-02-12 16:34
And what about current situation? Is bug still persist?

**Comment by M1cha** [comment] 2015-02-12 16:35
I'm currently investigating into this bug.

**Comment by kozachenko-m** [comment] 2015-02-12 16:37
nice to here that)) Do you have any news(good or bad) about it?

**Comment by M1cha** [comment] 2015-02-12 16:41
nope, not yet sry

**Comment by kozachenko-m** [comment] 2015-02-12 16:44
That's ok. We believe in you. Thank for your work.)

**Comment by M1cha** [comment] 2015-02-12 16:48
which build do you use? not even the latest one works?

**Comment by kozachenko-m** [comment] 2015-02-12 17:08
As for me, mi2- is main phone, so since I noticed the bug I changed the ROM and started to look for news about that issue. Last build, I tried was late January build: 24-th January, I think, but don't remember clearly.

**Comment by M1cha** [comment] 2015-02-12 17:32
I asked because I changed the RIL drivers from LGE to Xiaomi in December as a attempt to fix this.
Also this problem seems to be totally random. Some N4 users say the problem is gone, some say it's still there.

Maybe it's just time for me to make a stable CM12 where there problem hasn't been reported yet.

**Comment by kozachenko-m** [comment] 2015-02-12 17:36
From Russian 4pda forum I found some postst about that problem in CM12. I'm in the bus right now, I'll look for more info, when I come home.

**Comment by M1cha** [comment] 2015-02-12 17:38
the CM12 audio bug is different. It's because I updated the HAL. I'll fix that one for sure.

**Comment by ivba7** [comment] 2015-02-12 18:02
Problem still there. Tried latest nightly, updated play services and play store and immediately lost sound.

**Comment by M1cha** [comment] 2015-02-28 16:57
sry but I won't fix this. CM12 is pretty stable now and the call bugs are gone

**Closed as completed by M1cha** 2015-02-28 16:57 UTC
Labels: wontfix, cm-11.0, confirmed
