### ISSUE TITLE
On my Mi2S the headset doesn't work for phone calls. It does work for music. Before this beatiful Rom i used Miui,, the headset worked really well there

### ISSUE THREAD

**Issue by Vosje** [M1cha/android_device_xiaomi_aries#14] opened 2013-11-27 16:04 UTC
Sorry, saw there we're allready other bugs sent in fro this problem, you can ignore this one as it's completely identical

**Comment by M1cha** [comment] 2013-11-27 18:24
duplicate of #6

**Closed as completed by M1cha** 2013-11-27 18:24 UTC
Labels: duplicate
