### ISSUE TITLE
Wired headset buttons cause no reaction.

### ISSUE THREAD

**Issue by Giangiva** [M1cha/android_device_xiaomi_aries#5] opened 2013-10-18 07:05 UTC
I have a Mi2S 32GB bought directly from xiaomi.
I also own a wired headset from xiaomi as well, which is working fine with the MIUI rom (ok, it's not the best, but it's working... :-) )
When plugged in the phone using this rom, I can hear the sound through it, but pressing the buttons has no effect.
I even tried watching the logcat, but I couldn't notice any change in it when pressing the buttons on the headset.

**Comment by M1cha** [comment] 2013-10-20 20:31
This seems to be the device:
I/InputReader(  568): Device added: id=3, name='apq8064-tabla-snd-card Headset Jack', sources=0x80000000

I think we need to create "apq8064-tabla-snd-card_Headset_Jack.kl" but I don't know the keycodes for this device and I don't know how to find them, too. Any idea?

**Comment by Giangiva** [comment] 2013-10-21 06:27
I have installed the cm 10.2 4.3.1 made by cofface in my system2: do you think I can get those keycodes using that rom?
Or, since your kernel is different, also the keycodes will be different?
btw, is this a problem only on my phone (Mi2S) or do you see it in your one too (you own a Mi2, don't you)?
Another idea: since the device seems to be created, can't we read its events from any place in /proc or in /sys?

**Comment by M1cha** [comment] 2013-10-23 08:55
I don't know if that works but you could try to get the keycodes via CWM.
advanced -> key test

**Comment by Giangiva** [comment] 2013-10-23 09:47
I tried it, but I got no reaction... :-(
The only code I got is the one for the 'back' key that I pressed to get out of the key test.

**Comment by M1cha** [comment] 2013-10-25 13:44
Does this app show the keycodes?
https://github.com/chrisboyle/keytest/downloads

**Comment by Giangiva** [comment] 2013-10-26 06:02
Unfortunately, not.
I can see other buttons with it: menu, back, but nothing happens when I press the keys on the headset.

**Comment by ghost** [comment] 2013-11-22 14:31
I have Klipsch earphones (w/ microphone and single button), which work fully on Miui w/ MI2S 32GB.

The "key test.apk" does not register any key press for the earphones button, while CWM reports ScanCode 256.

Just for the information of those interested: from the view point of plug wiring, MI2 seems compatible with iPhone with the only difference that volume +/- buttons (if exist) do not work on Android. This is IMHO true for any recent Android devices (e.g. last "smart" Samsung with the old "nokia" style was SGS i9000).  There are available simple adapters, which switch the mic & ground. The two existing "standards" are shown at the attached picture.
![zs-1](https://f.cloud.github.com/assets/6010689/1601103/3f85e086-5382-11e3-9555-f9b715ead99e.jpg)

**Comment by ghost** [comment] 2013-11-22 17:30
Ivan's ROM (see the other issue #6 ) reads the Scan Code as 226.
![ivan_button](https://f.cloud.github.com/assets/6010689/1602646/c039bbbc-539b-11e3-9f6b-e7d367914706.jpg)

**Comment by Giangiva** [comment] 2013-12-07 09:35
Hi M1cha,

today, with the 3/12/2013 release, I tried again the wired headset: no luck.
Then I tried with the key test in the cwm recovery: success!
The "play" button is code 256
The "forward" button is code 257
The "rewind" button is code 258
Given that, now, the system seems to be able to read the keys, how can I "convince" the apps to do something with these keys?

**Comment by Vosje** [comment] 2013-12-12 09:50
Hi Guys,

I have the same problem, am using an IPhone headset. During Phone calls the mic doesn't work. I can hear the otter person, they can't hear me

**Comment by M1cha** [comment] 2013-12-12 10:01
Vosje: that's a different problem and has nothing to do with this issue.

**Comment by Vosje** [comment] 2013-12-12 10:12
Ok sorry, I'll make a new post for this one then.

**Comment by Vosje** [comment] 2013-12-13 10:42
I’ve tested this, the internal mic doesn’t work when I connect my headset 

Van: M1cha [mailto:notifications@github.com] 
Verzonden: donderdag 12 december 2013 11:02
Aan: M1cha/android_device_xiaomi_aries
CC: Vosje
Onderwerp: Re: [android_device_xiaomi_aries] Wired headset buttons cause no reaction. (#5)

Vosje: that's a different problem and has nothing to do with this issue.

**Comment by M1cha** [comment] 2013-12-16 17:21
does that work? 
http://d-h.st/Fw5

**Comment by ghost** [comment] 2013-12-16 18:41
Nope. Flashed it and cannot see any change. No reaction, Key Test apk does not notice the presses either.

**Comment by DaRoni** [comment] 2013-12-17 12:09
the same problem with headphones on mi2, headphones from xiaomi
http://www.ebay.com/itm/New-Xiaomi-PISTON-Earphones-Headset-Headphones-w-wire-control-for-MI2-MI2A-MI2S-/290950250173
upd1
keycode_test-signed.zip did not help
upd2
here can be help with the problem.
https://www.dropbox.com/s/jrczribp3745hbh/2013-12-17_183806_logcat.txt
https://www.dropbox.com/s/k563o4lay0e0pyv/2013-12-17_183817_dmesg.txt
https://www.dropbox.com/s/eq1b3bbcw9ogms6/2013-12-17_183826_bugreport.txt

**Comment by M1cha** [comment] 2014-01-19 20:18
can u confirm that this is fixed in latest build from linuxx?

**Comment by jrizzoli** [comment] 2014-01-20 06:28
I don't have buttons on my headset, so I can't try, but if it should works if m1cha pushed the commit before 18-01-14 22:30 (GMT+1)

**Comment by DaRoni** [comment] 2014-01-20 07:36
Works only increase the volume button.
Play button and decrease the volume button does not work.
flashed cm-11-20140118-UNOFFICIAL-ARIS + pa_gapps-modular-full-4.4.2-20140117-signed, checked with Apollo.

**Comment by M1cha** [comment] 2014-01-20 07:52
dump the keycodes in CWM, and check with input test apps if the buttons are at least recognized

**Comment by DaRoni** [comment] 2014-01-22 16:50
same as before
The "play" button is code 256
The "forward" button is code 257
The "rewind" button is code 258

**Comment by M1cha** [comment] 2014-01-22 17:14
ah ok that's the reason. u don't have play, vol+ and vol- u have play, forward,rewind

**Comment by M1cha** [comment] 2014-01-22 17:21
ah and btw please ceck the keycodes with the app I've posted above.
CWM uses 4.1 kernel and shows different keycodes

**Comment by ghost** [comment] 2014-01-22 17:44
Just for those interested: it appears that "vol +" and "vol -" on Apple headset use different resistance (Ohm) values than "rewind" and "forward" on some Android headsets. And what may work on one Android, may not necessarily work on another Android.

I wonder, if the driver/hw in Mi2 can catch all the "key presses" of various headsets or just some. (I have only a single button headset, however.)

At least Play/Pause button seems to be the same accross platforms.

http://www.instructables.com/id/Galaxy-Nexus-and-others-headset-remote-with-medi/

**Comment by DaRoni** [comment] 2014-01-23 01:11
V+   https://www.dropbox.com/s/64lzhx2vgo54iib/22012014086.JPG
play https://www.dropbox.com/s/nkalzsdu5ccerzu/22012014087.JPG
V-  no reaction  https://www.dropbox.com/s/0bovsmku7398d5a/22012014088.JPG

**Comment by ghost** [comment] 2014-02-01 17:51
On CM @ 2014-01-25: I was surprised, that presses of the single button on my headset generates different scanCodes in Keytest.apkg, namely 256, 257, 258, 263. Quite randomly, without a clear pattern. scanCode 263 maps to Keycode 25 (volume down), scanCode 257 maps to Keycode 79 (headsethook), while the others are not mapped to any Keycode. I have shot a screen cast, if needed.

On ivan's ROM [1], the presses of the button alwaysgenerate the same scanCode 226 (which is mapped to Key code 79.

http://xiaomi.eu/community/threads/aosp-4-4-kitkat-rom-aosp-by-ivan.22682/page-10#post-195465

Could it be a driver issue?

Edit1: the same headset (Klipsch) behaves the same on another Mi2S phone with M1cha's CM11. A different headset (iFrogz audio) generates just a single scanCode 256 on the same ROM.

**Comment by ghost** [comment] 2014-02-05 19:42
@M1cha: how about opening a thread at xiaomi.eu to find out what scanCodes exist for various users with current release of your CM11?

For myself, I am just fine to edit apq8064-tabla-snd-card_Headset_Jack.kl after flashing CM11, but resolving the bug might be a bit better ;-)

**Comment by LobsterJohnson** [comment] 2014-05-25 14:49
Here is what I got with my philips uptown using the play/answer button with CM11 by cofface:

Keycode:79
KeyEvent: KeyEvent { action=ACTION_DOWN,
keyCode=KEYCODE_HEADSETHOOK,
scanCode=226, metaState=0, flags=0x8,
repeat=226, metaState=0, flags=0x8,
repeatCount=0, eventTime71612207,
downTime=71612207, deviceld=3, source0x101

**Comment by shivwolf** [comment] 2014-07-08 22:18
Same problem.
Me on mi2s with dual boot:
On cyanogenmod 11-20140619-nightly-aries:
- = -
  Play works
- don't works
  On miui v5 works fine.

Got the m1cha recovery.
Can I test something to you?

**Comment by shivwolf** [comment] 2014-07-08 22:23
Same problem.
Me on mi2s with dual boot:
On cyanogenmod 11-20140619-nightly-aries:
Volume + works as -
Play works ok
Volume - don't works
On miui v5 works fine.

Got the m1cha recovery.
Can I test something to you?

**Comment by disparil** [comment] 2014-08-28 14:11
Same problem here
Me on Mi2 with WIUI v5 KK 4.4.4 (based on CM11)

Volume + works as -
Play works ok
Volume - don't works

**Comment by JustAMan** [comment] 2014-09-03 21:02
I have Xiaomi Gold Pistons (headset with 3 buttons) and Xiaomi MiKey (in-jack button), both don't work correctly in CM11 (but work okay in stock MIUI, so hardware is okay).

No buttons seem to work (not even play/pause button on the headset, at least it won't control Apollo player).

I tried testing buttons in the CWM I have (some 6.0.x I believe), and it detects play and some volume (up or down - don't remember), but doesn't detect neither other volume button nor MiKey presses.

I'm using CM11 m8 snapshot.

How can I debug this thing? :)

P.S. Tried KeyTest app - it, too, detects volume up and play/pause presses (though it says "keyCode=KEYCODE_UNKNOWN" for both), scan code for volume up is 262, for play is 256.

**Comment by JustAMan** [comment] 2014-09-07 12:10
I think I see why Xiaomi headset buttons don't work - they use different resistance values for buttons compared to what the kernel in @M1cha build expects.

I've compared "sound/soc/msm/apq8064.c" in kernel source between @M1cha version and official (at least that's what I found) version from Xiaomi (https://github.com/MiCode/mi2_kernel), and they differ in the function that I understand as setting button resistances: at 

``` c
static void *def_tabla_mbhc_cal(void)
```

somewhere in its code there is this:

| Xiaomi | M1cha |
| --- | --- |
| btn_low[0] = -75; | btn_low[0] = -50; |
| btn_high[0] = 150; | btn_high[0] = 10; |
| btn_low[1] = 151; | btn_low[1] = 11; |
| btn_high[1] = 330; | btn_high[1] = 52; |
| btn_low[2] = 331; | btn_low[2] = 53; |
| btn_high[2] = 655; | btn_high[2] = 94; |
| btn_low[3] = 21; | btn_low[3] = 95; |
| btn_high[3] = 62; | btn_high[3] = 133; |
| btn_low[4] = 154; | btn_low[4] = 134; |
| btn_high[4] = 181; | btn_high[4] = 171; |
| btn_low[5] = 182; | btn_low[5] = 172; |
| btn_high[5] = 218; | btn_high[5] = 208; |
| btn_low[6] = 219; | btn_low[6] = 209; |
| btn_high[6] = 254; | btn_high[6] = 244; |
| btn_low[7] = 63; | btn_low[7] = 245; |
| btn_high[7] = 104; | btn_high[7] = 330; |

I think I may try to compile my own fork of @M1cha kernel with those lines taken from Xiaomi to fix Xiaomi headset buttons.

**Comment by JustAMan** [comment] 2014-09-07 21:09
I've fixed (at least on my device) both Xiaomi Pistons (gold, v.2) and MiKey with CM11 m8.
I had to re-compile the kernel (with some changes) and to change keylayout file.

Pull requests are:
https://github.com/M1cha/android_kernel_xiaomi_aries/pull/2
https://github.com/M1cha/android_device_xiaomi_aries/pull/62

**Comment by JustAMan** [comment] 2014-09-08 10:25
If anyone is using CM11 m8 stable release - here's CWM-flashable patch that fixes MiKey and Xiaomi Pistons
https://github.com/JustAMan/android_kernel_xiaomi_aries/releases/download/pistons-mikey-fixed/cm11-pistons-mikey-fix.zip

At least on my Mi2S it works perfectly after that. Give it a try and let me know if it fails.

**Comment by shivwolf** [comment] 2014-09-08 10:36
Thank you JustAMan, i´ll try it this evening and comment here.
Is it just a patch? Or is a complete recovery for pistons & mikey?

**Comment by JustAMan** [comment] 2014-09-08 10:37
It's new kernel (based on latest cm-11 version from M1cha repos) which fixes buttons on the headset and MiKey (at least on my device).

It should be applied via CWM just like any other update package - via "install zip from sdcard" menu.

**Comment by shivwolf** [comment] 2014-09-08 10:47
Perfect, I´ll give a try!

**Comment by shivwolf** [comment] 2014-09-08 15:42
Works fine on my mi2s (32GB)
Cm11 snapshot + Cwm recovery(m1cha)

A lot of thanks JustAMan & Co.

**Comment by jrizzoli** [comment] 2014-09-08 15:45
Can I commit this to cm for u? (I'll give u credits ofc)

**Comment by M1cha** [comment] 2014-09-08 15:47
It has been merged to CM already.

**Closed as completed by M1cha** 2014-09-08 15:47 UTC
Labels: bug, cm-11.0, confirmed

**Comment by jrizzoli** [comment] 2014-09-08 15:49
Better :P

2014-09-08 17:47 GMT+02:00 M1cha notifications@github.com:

**Comment by archont00** [comment] 2014-09-08 16:49
Hello guys, the new values for btn_[high|low] have an affect on scan codes.

My earbuds report various scan codes for a single button press - IMHO the precision of Mi2s is better than the precision of resistors in the earbuds. I can simply assign the same Key Code to the various Scan Codes in "apq8064...Button_Jack.kl" config file to resolve the problem for myself, though it would be better to have the "bigger" config file available for everyone.

This is a good solution as long as the reported scan codes do not overlap with Volume Up/Down of other earbuds.

To check if there is an overlap or not, I would appreciate if you can report again the Scan Codes for your earbuds.

**After installing the patched kernel** (or at least CM nightly 2014-09-09), **will you please run the Key Test app and report:**

```
Earbud name
Button   ScanCode
-----------------------------------------------------
Klipsch for Android with microphone
Play/Pause  256 (most often), 257 , 258, 263 (rarely)

Apple earbuds with microphone
Play/Pause   256
Volume Up  - ignored
Volume Down - ignored
```

The Volume Up/Down being ignored is expected behaviour, since Apple uses a different technology for these buttons (probably capacitators instead of resistors).

Thnx a lot!

**Comment by shivwolf** [comment] 2014-09-09 07:31
Earbud: Xiaomi Piston

Keytest inside recovery(m1cha):
up - 263
down - ignored
play - 257

keytest.apk in CM 11 + JustAMan patch:
up - 24
down - 25
play - 79

keytest.apk in miui
up - 24
down - 25
play - 79

**Comment by JustAMan** [comment] 2014-09-09 16:15
@milankni 
Play/pause button should be as easy as making 0 resistance, so it should always be scan code 256.

I can provide you a "debug" kernel which dumps measured voltage in dmesg, and we can try to see if specific values need to be tuned.

**Comment by archont00** [comment] 2014-09-10 07:53
@JustAMan 
You are about right, however on xda it is mentioned that the resistor value for pressed play/pause button is not neccessarily close to 0 Ohm (short-circuit), E.g. Samsung earbuds have slightly higher resistence.

http://forum.xda-developers.com/showpost.php?p=34185923&postcount=24

My Klipsch earbuds may have a buggy button (worn out?) leading to some inconsistent values and now I guess a workaround of assigning mutliple scanCodes to a single Key Code should not be pushed upstream.
**Anyway, if you are so kind and provide me with the debug kernel, I would be happy to see the voltages.** (I assume there is not a direct correlation between voltage/resistence and scanCodes. I will try to look into the code if I can find the mapping).

**Comment by M1cha** [comment] 2014-09-10 08:07
@milankni does you have different scancodes in MIUI, too? It could be a kernel bug.

**Comment by JustAMan** [comment] 2014-09-10 09:52
@milankni 
Here you go: https://github.com/JustAMan/android_kernel_xiaomi_aries/releases/download/pistons-mikey-fixed/cm11-debug-buttons.zip

You just flash it with CWM, boot your phone, wait till it finishes booting, plug your headset and press some buttons.
Then with "adb shell su -c dmesg >dmesg.txt" you get dmesg and search for "mv=" string there, it would be some voltage measurements made by the kernel (either when you plug something - it measures voltage to understand what you've plugged, or when you press a button).

**Comment by shivwolf** [comment] 2014-09-10 12:02
Im trying to test things for u guys, but isn´t working too well.

I´ve installed the test program by JustAMan, entered the console and when I wrote the line, I get the message:
"can´t create dmesg.txt :Read-only file system"

I´d tried 
adb shell su -c dmesg >/mnt/sdcard/prueba.txt
and this responses:
Error: device not found.
But this time I get the "prueba.txt" file, but inside, only appears
_daemon not running.starting it now on port 5038 \* 
*daemon started succesfully_

Any tip?

**Comment by M1cha** [comment] 2014-09-10 12:08
adb is used to establish a connection with a android device. Since you're using terminal emulator you don't need that connection. Just remove the "adb shell" part of your command.

**Comment by shivwolf** [comment] 2014-09-10 12:54
I´ve tried and get this (if search by "mv", I got a lot of lines, I think the good ones are lines with "determine button")

Here they are (only copy those who arent repeated)

<7>[   66.280517] tabla_determine_button: micmv=18, btn=0  
<7>[   66.293151] tabla_determine_button: micmv=16, btn=0  
<7>[   72.411285] tabla_determine_button: micmv=272, btn=1  
<7>[   73.271118] tabla_determine_button: micmv=253, btn=1  
<7>[   74.972534] tabla_determine_button: micmv=598, btn=2   

And this, I suppose that they are detecting when I plug it:
<7>[   60.508209] tabla_codec_get_plug_type: Detect attempt 0, detected Headset (mic_mv=1386)
<7>[   60.508209] tabla_codec_get_plug_type: Detect attempt 1, detected Headset (mic_mv=1556)
<7>[   60.508209] tabla_codec_get_plug_type: Detect attempt 2, detected Headset (mic_mv=2012)
<7>[   60.508209] tabla_codec_get_plug_type: Detect attempt 3, detected Headset (mic_mv=2153)
<7>[   60.508239] tabla_codec_get_plug_type: Detected plug type 1

I hope will be helpful

**Comment by JustAMan** [comment] 2014-09-10 13:22
@shivwolf 
Are you trying to demonstrate something not working? I was under impression you have (like me) Xiaomi Pistons and they work with my patch, so I was expecting some values from those for whom the patch doesn't work (like those with Klipsch earpods or something).

Nevertheless it's good to see you were able to use my debug kernel :)

**Comment by shivwolf** [comment] 2014-09-10 13:31
Hahaha
Im trying to be helpful in any way.

By the way,im trying to learn how to build a ROM,how it works, and how to use some commands or debugging tools.
Thats why i try to use all i found here

But you are un true, got the pistons and now are working.
And now ive learned how to use your debug.
Thanks for it and,of course,for the patch

**Comment by archont00** [comment] 2014-09-10 14:05
@M1cha 
I tried w/ latest MIUI (international edition) and the behaviour of the Klipsch earbuds is the same.

**Comment by JustAMan** [comment] 2014-09-10 20:13
@shivwolf 
You're welcome :) Both in using the patch and learning how to use other stuff.

@milankni 
Can you follow the instructions I've written above about using debug kernel and getting the debug values for your Klipsch buds (just like shivwolf did)?

**Comment by archont00** [comment] 2014-09-11 07:34
@JustAMan 
Here it is - I have grepped the dmesg output for "mv", while repeatedly pressing the button on Klipsch as crazy ;)

```
<7>[  489.091583] tabla_codec_get_plug_type: Detect attempt 0, detected Headset (mic_mv=1119)
<7>[  489.091613] tabla_codec_get_plug_type: Detect attempt 1, detected Headset (mic_mv=1360)
<7>[  489.091644] tabla_codec_get_plug_type: Detect attempt 2, detected Headset (mic_mv=1853)
<7>[  489.091674] tabla_codec_get_plug_type: Detect attempt 3, detected Headset (mic_mv=2009)
<7>[  494.595703] tabla_determine_button: micmv=199, btn=1
<7>[  494.609374] tabla_determine_button: micmv=20, btn=0
<7>[  494.883850] tabla_determine_button: micmv=42, btn=0
<7>[  494.897521] tabla_determine_button: micmv=619, btn=2
<7>[  498.459533] tabla_determine_button: micmv=12, btn=0
<7>[  498.473724] tabla_determine_button: micmv=9, btn=0
<7>[  500.421539] tabla_determine_button: micmv=12, btn=0
<7>[  500.436096] tabla_determine_button: micmv=12, btn=0
<7>[  507.923431] tabla_determine_button: micmv=12, btn=0
<7>[  507.936157] tabla_determine_button: micmv=16, btn=0
<7>[  508.153350] tabla_determine_button: micmv=9, btn=0
<7>[  508.166076] tabla_determine_button: micmv=9, btn=0
<7>[  509.486694] tabla_determine_button: micmv=131, btn=0
<7>[  509.501861] tabla_determine_button: micmv=157, btn=1
<7>[  509.729492] tabla_determine_button: micmv=38, btn=0
<7>[  509.743652] tabla_determine_button: micmv=20, btn=0
<7>[  509.963378] tabla_determine_button: micmv=243, btn=1
<7>[  509.976104] tabla_determine_button: micmv=254, btn=1
<7>[  511.812713] tabla_determine_button: micmv=34, btn=0
<7>[  511.826629] tabla_determine_button: micmv=31, btn=0
<7>[  515.267272] tabla_determine_button: micmv=16, btn=0
<7>[  515.283233] tabla_determine_button: micmv=23, btn=0
<7>[  515.826446] tabla_determine_button: micmv=12, btn=0
<7>[  515.839843] tabla_determine_button: micmv=12, btn=0
<7>[  517.656036] tabla_determine_button: micmv=9, btn=0
<7>[  517.670196] tabla_determine_button: micmv=9, btn=0
<7>[  518.124786] tabla_determine_button: micmv=9, btn=0
<7>[  518.138671] tabla_determine_button: micmv=9, btn=0
<7>[  519.698608] tabla_determine_button: micmv=93, btn=0
<7>[  519.711395] tabla_determine_button: micmv=58, btn=0
<7>[  520.309265] tabla_determine_button: micmv=42, btn=0
<7>[  520.323699] tabla_determine_button: micmv=45, btn=0
<7>[  520.797851] tabla_determine_button: micmv=27, btn=0
<7>[  520.811981] tabla_determine_button: micmv=27, btn=0
<7>[  521.732177] tabla_determine_button: micmv=12, btn=0
<7>[  521.744934] tabla_determine_button: micmv=12, btn=0
<7>[  522.722534] tabla_determine_button: micmv=283, btn=1
<7>[  522.736755] tabla_determine_button: micmv=300, btn=1
<7>[  523.511169] tabla_determine_button: micmv=42, btn=0
<7>[  523.524810] tabla_determine_button: micmv=16, btn=0
<7>[  523.845031] tabla_determine_button: micmv=16, btn=0
<7>[  523.859039] tabla_determine_button: micmv=12, btn=0
<7>[  524.149810] tabla_determine_button: micmv=20, btn=0
<7>[  524.163848] tabla_determine_button: micmv=20, btn=0
<7>[  524.363250] tabla_determine_button: micmv=38, btn=0
<7>[  524.375976] tabla_determine_button: micmv=34, btn=0
<7>[  526.242889] tabla_determine_button: micmv=166, btn=1
<7>[  526.257049] tabla_determine_button: micmv=106, btn=0
<7>[  526.554504] tabla_determine_button: micmv=10, btn=0
<7>[  526.567413] tabla_determine_button: micmv=9, btn=0
<7>[  526.824737] tabla_determine_button: micmv=9, btn=0
<7>[  526.837951] tabla_determine_button: micmv=9, btn=0
<7>[  527.118927] tabla_determine_button: micmv=9, btn=0
<7>[  527.133697] tabla_determine_button: micmv=9, btn=0
<7>[  527.652038] tabla_determine_button: micmv=20, btn=0
<7>[  527.664794] tabla_determine_button: micmv=23, btn=0
<7>[  528.399047] tabla_determine_button: micmv=34, btn=0
<7>[  528.412841] tabla_determine_button: micmv=31, btn=0
<7>[  528.693328] tabla_determine_button: micmv=20, btn=0
<7>[  528.706054] tabla_determine_button: micmv=20, btn=0
<7>[  529.029602] tabla_determine_button: micmv=38, btn=0
<7>[  529.043212] tabla_determine_button: micmv=38, btn=0
<7>[  529.744415] tabla_determine_button: micmv=14, btn=0
<7>[  529.757476] tabla_determine_button: micmv=12, btn=0
<7>[  530.609344] tabla_determine_button: micmv=27, btn=0
<7>[  530.623565] tabla_determine_button: micmv=20, btn=0
<7>[  530.969604] tabla_determine_button: micmv=27, btn=0
<7>[  530.983703] tabla_determine_button: micmv=23, btn=0
<7>[  531.779663] tabla_determine_button: micmv=31, btn=0
<7>[  531.792388] tabla_determine_button: micmv=29, btn=0
<7>[  533.385070] tabla_determine_button: micmv=12, btn=0
<7>[  533.399200] tabla_determine_button: micmv=16, btn=0
<7>[  534.037261] tabla_determine_button: micmv=20, btn=0
<7>[  534.051513] tabla_determine_button: micmv=23, btn=0
<7>[  534.409790] tabla_determine_button: micmv=23, btn=0
<7>[  534.423706] tabla_determine_button: micmv=23, btn=0
<7>[  534.699676] tabla_determine_button: micmv=16, btn=0
<7>[  534.713806] tabla_determine_button: micmv=12, btn=0
<7>[  535.054351] tabla_determine_button: micmv=12, btn=0
<7>[  535.067291] tabla_determine_button: micmv=12, btn=0
<7>[  535.934570] tabla_determine_button: micmv=9, btn=0
<7>[  535.948547] tabla_determine_button: micmv=9, btn=0
<7>[  536.956268] tabla_determine_button: micmv=16, btn=0
<7>[  536.969879] tabla_determine_button: micmv=16, btn=0
<7>[  537.304870] tabla_determine_button: micmv=243, btn=1
<7>[  537.318725] tabla_determine_button: micmv=247, btn=1
<7>[  537.574371] tabla_determine_button: micmv=258, btn=1
<7>[  537.587188] tabla_determine_button: micmv=245, btn=1
<7>[  537.929840] tabla_determine_button: micmv=34, btn=0
<7>[  537.942657] tabla_determine_button: micmv=34, btn=0
<7>[  538.614227] tabla_determine_button: micmv=38, btn=0
<7>[  538.629669] tabla_determine_button: micmv=38, btn=0
<7>[  539.889343] tabla_determine_button: micmv=12, btn=0
<7>[  539.903594] tabla_determine_button: micmv=12, btn=0
<7>[  540.193237] tabla_determine_button: micmv=27, btn=0
<7>[  540.206115] tabla_determine_button: micmv=16, btn=0
<7>[  540.489593] tabla_determine_button: micmv=23, btn=0
<7>[  540.503784] tabla_determine_button: micmv=21, btn=0
<7>[  540.926147] tabla_determine_button: micmv=131, btn=0
<7>[  540.940368] tabla_determine_button: micmv=65, btn=0
<7>[  541.461761] tabla_determine_button: micmv=60, btn=0
<7>[  541.476593] tabla_determine_button: micmv=51, btn=0
<7>[  542.333953] tabla_determine_button: micmv=31, btn=0
<7>[  542.347686] tabla_determine_button: micmv=29, btn=0
<7>[  543.466766] tabla_determine_button: micmv=9, btn=0
<7>[  543.481262] tabla_determine_button: micmv=9, btn=0
<7>[  544.011840] tabla_determine_button: micmv=219, btn=1
<7>[  544.026062] tabla_determine_button: micmv=115, btn=0
<7>[  544.491027] tabla_determine_button: micmv=113, btn=0
<7>[  544.503753] tabla_determine_button: micmv=108, btn=0
<7>[  545.112915] tabla_determine_button: micmv=76, btn=0
<7>[  545.129272] tabla_determine_button: micmv=65, btn=0
<7>[  546.000793] tabla_determine_button: micmv=9, btn=0
<7>[  546.014923] tabla_determine_button: micmv=9, btn=0
<7>[  546.374816] tabla_determine_button: micmv=73, btn=0
<7>[  546.389312] tabla_determine_button: micmv=18, btn=0
<7>[  547.033630] tabla_determine_button: micmv=9, btn=0
<7>[  547.048583] tabla_determine_button: micmv=9, btn=0
<7>[  547.263305] tabla_determine_button: micmv=9, btn=0
<7>[  547.276031] tabla_determine_button: micmv=9, btn=0
<7>[  547.711761] tabla_determine_button: micmv=135, btn=0
<7>[  547.725921] tabla_determine_button: couldn't find button number for mic mv 1137
<7>[  547.725952] tabla_determine_button: micmv=1137, btn=-1
<7>[  548.178436] tabla_determine_button: micmv=18, btn=0
<7>[  548.192687] tabla_determine_button: micmv=16, btn=0
```

**Comment by JustAMan** [comment] 2014-09-11 09:15
@milankni 
Does your Klipsch has one button only? The log you posted suggests yours headset has several buttons... if you have one button - most likely this log means that contacts within it are really worn out.

**Comment by archont00** [comment] 2014-09-11 12:15
My Klipsch are the Android variant with a single button. I opened the button+mike box and cleaned the micro switch (similar like here https://d3nevzfk7ii3be.cloudfront.net/igi/PnTfYP4BawrolrqD , just a bit tinier). Now it seems that the same scanCode is always returned.
It must have oxidised, not worn out. Anyway, we'll see after some time.

**Comment by JustAMan** [comment] 2014-09-11 12:55
@milankni 
Great to hear that your problem seems to be fixed now :)
